require(readxl)
url <- "https://github.com/Smolski/livroavancado/raw/master/dbc.xls"
install.packages("hydroGOF")
library("hydroGOF")
library("Metrics")
destfile <- "dbc.xls"
curl::curl_download(url, destfile)
data<-read.table("clipboard",h=T)
summary(DBC)
attach(DBC)
anova=aov(DP~TRATAMENTO+BLOCO)
summary(anova)
attach(DBC)
HSD.test(anova,as.factor("TRATAMENTO"),console=TRUE)

data<-read.table("clipboard",h=T)
summary(data)
model<-lm(data$THETA ~ data$V9 + I(data$V9^2))
summary(model)
confint(model,level=0.95)
d(data$V1,data$THETA)
cor.test(data$THETA,data$V1,method="spearm")
mae(data$THETA,data$THETAJ)
rmse(data$THETA,data$THETAJ)
